name: tiktok_clone
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  supabase_flutter: ^2.5.0
  supabase_auth_ui: ^0.5.5
  video_player: ^2.8.6
  image_picker: ^1.1.1
  provider: ^6.1.2
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
